services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    network_mode: host
    privileged: true
    #restart: always
    shm_size: '2gb'
    environment:
      - GO2RTC_CONFIG=/config/go2rtc.yaml
    devices:
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2
    volumes:
      - ./config:/config

  ts-bridge:
    image: tailscale/tailscale:latest
    container_name: ts-bridge
    hostname: keime-docker
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./ts-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #restart: always

  robot-app:
    image: python:3.11-slim
    container_name: robot-control
    volumes:
      - .:/app
    working_dir: /app
    privileged: true
    devices:
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0001KJH-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0001KJH-if00-port0"
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B003725S-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B003725S-if00-port0"
    ports:
      - "5000:5000"
    restart: always
    # Dockerfileなしで動かすための「ワンライナー」コマンド
    # 1. 必要なOSライブラリ(OpenCV用)をインストール
    # 2. Pythonライブラリをインストール
    # 3. スケッチを実行
    command: >
      sh -c "apt-get update && apt-get install -y libgl1 libglib2.0-0 &&
             pip install --no-cache-dir flask flask-cors opencv-contrib-python numpy pyserial &&
             python src/integrated_server_v9.py"