services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    network_mode: host
    privileged: true
    restart: always
    shm_size: '2gb'
    environment:
      - GO2RTC_CONFIG=/config/go2rtc.yaml
    devices:
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2  # 追加：ロボット制御用カメラも必要なら
    volumes:
      - ./config:/config

  ts-bridge:
    image: tailscale/tailscale:latest
    container_name: ts-bridge
    hostname: keime-docker
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./ts-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always

  robot-app:
    build: .  # カレントディレクトリのDockerfileを使用
    container_name: robot-control
    volumes:
      - .:/app
    privileged: true
    devices:
      # スケッチ内で指定しているFTDIのデバイスIDをマッピング
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0001KJH-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0001KJH-if00-port0"
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B003725S-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B003725S-if00-port0"
    ports:
      - "5000:5000"
    # venv内のpythonを使用してsrcディレクトリのスケッチを実行
    command: /opt/venv/bin/python src/integrated_server_v9.py
    restart: always